local _, ns = ...

-- Retail 12.1 additions audited against the current Wowhead Midnight guides.
-- This file intentionally uses new IDs only.  Stale rows from the older
-- catalogue are listed in the hand-off audit and must be removed there rather
-- than shadowed here.
ns.AdditionalCapabilityGroups = ns.AdditionalCapabilityGroups or {}

-- The exact trait IDs for the new Devourer/Vengeance hero routes are client
-- data and should be filled by the live trait scanner when available.  The
-- rules below remain ungated for core spells; hero-gated rows use the existing
-- verified capability names where possible.

local rules = {
    -- Devastation Evoker (1467): 12.1 priority and cooldown coverage.
    { id="audit12_dev_deep_breath", spec=1467, spell="Deep Breath", name="Deep Breath", moment="Cast", event="SUCCEEDED", spellIDs={357210}, capability="scalecommander", cue="draconic", preset="subtle", cooldown=2.5, defaultOn=true, defaultSounds={4555731,4612501}, defaultDelays={0,100}, description="Scalecommander's instant Deep Breath activation." },
    { id="audit12_dev_tip_scales", spec=1467, spell="Tip the Scales", name="Tip the Scales", moment="Cast", event="SUCCEEDED", spellIDs={370553}, cue="major", preset="subtle", cooldown=3, defaultOn=true, defaultSounds={4686040,4558561}, defaultDelays={0,90}, description="Instant empower shortcut before a key breath or surge." },
    { id="audit12_dev_pyre", spec=1467, spell="Pyre", name="Pyre", moment="Cast", event="SUCCEEDED", spellIDs={357211}, cue="deepfire", preset="medium", cooldown=0.9, defaultOn=true, defaultSounds={4553204,4569652}, defaultDelays={0,90}, description="Essence spender launch; periodic effects stay silent." },
    { id="audit12_dev_living_flame", spec=1467, spell="Living Flame", name="Living Flame", moment="Cast", event="SUCCEEDED", spellIDs={361469}, cue="deepfire", preset="medium", cooldown=1.2, defaultOn=false, defaultSounds={4553204}, defaultDelays={0}, description="Two-second filler cast and Essence Burst generator." },
    { id="audit12_dev_azure_strike", spec=1467, spell="Azure Strike", name="Azure Strike", moment="Cast", event="SUCCEEDED", spellIDs={362969}, cue="arcane", preset="medium", cooldown=1.2, defaultOn=false, defaultSounds={4558551}, defaultDelays={0}, description="Instant movement filler; disabled by default to avoid filler spam." },
    { id="audit12_dev_unbound_flame", spec=1467, spell="Unbound Flame", name="Unbound Flame", moment="Cast", event="SUCCEEDED", spellIDs={1292321}, cue="deepfire", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={4553204,4569652}, defaultDelays={0,90}, description="Post-Dragonrage instant replacement cast." },
    { id="audit12_dev_hover", spec=1467, spell="Hover", name="Hover", moment="Cast", event="SUCCEEDED", spellIDs={358267}, cue="draconic", preset="subtle", cooldown=1.5, defaultOn=false, defaultSounds={4555731}, defaultDelays={0}, description="Instant movement/casting utility." },
    { id="audit12_dev_mass_disintegrate", spec=1467, spell="Mass Disintegrate", name="Mass Disintegrate", moment="Cast", event="SUCCEEDED", spellIDs={436335}, capability="scalecommander", cue="arcane", preset="medium", cooldown=1.5, defaultOn=true, defaultSounds={5520037,4686044}, defaultDelays={0,100}, description="Scalecommander's current Mass Disintegrate talent moment." },

    -- Preservation Evoker (1468): healing loop, mobility and utility.
    { id="audit12_pres_reversion", spec=1468, spell="Reversion", name="Reversion", moment="Cast", event="SUCCEEDED", spellIDs={367364}, cue="bronzeEcho", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={4558551,4558561}, defaultDelays={0,70}, description="Instant Echo-consuming HoT." },
    { id="audit12_pres_living_flame", spec=1468, spell="Living Flame", name="Living Flame", moment="Cast", event="SUCCEEDED", spellIDs={361469}, cue="nature", preset="medium", cooldown=1.2, defaultOn=false, defaultSounds={4614320}, defaultDelays={0}, description="Two-second filler and Essence Burst generator." },
    { id="audit12_pres_tip_scales", spec=1468, spell="Tip the Scales", name="Tip the Scales", moment="Cast", event="SUCCEEDED", spellIDs={370553}, cue="major", preset="subtle", cooldown=3, defaultOn=true, defaultSounds={4686040,4558561}, defaultDelays={0,90}, description="Instant maximum-rank empower shortcut." },
    { id="audit12_pres_hover", spec=1468, spell="Hover", name="Hover", moment="Cast", event="SUCCEEDED", spellIDs={358267}, cue="draconic", preset="subtle", cooldown=1.5, defaultOn=false, defaultSounds={4555731}, defaultDelays={0}, description="Instant movement and cast-while-moving utility." },
    { id="audit12_pres_rescue", spec=1468, spell="Rescue", name="Rescue", moment="Cast", event="SUCCEEDED", spellIDs={370665}, cue="nature", preset="subtle", cooldown=2, defaultOn=false, defaultSounds={4614320,903900}, defaultDelays={0,90}, description="Optional instant ally movement utility." },
    { id="audit12_pres_zephyr", spec=1468, spell="Zephyr", name="Zephyr", moment="Cast", event="SUCCEEDED", spellIDs={374227}, cue="draconic", preset="subtle", cooldown=3, defaultOn=true, defaultSounds={4555731,5259954}, defaultDelays={0,100}, description="Instant group mobility/defensive cooldown." },
    { id="audit12_pres_cauterizing_flames", spec=1468, spell="Cauterizing Flames", name="Cauterizing Flames", moment="Cast", event="SUCCEEDED", spellIDs={374251}, cue="deepfire", preset="subtle", cooldown=3, defaultOn=false, defaultSounds={4553204,4569652}, defaultDelays={0,100}, description="Optional instant dispel/bleed utility, including Stasis setups." },

    -- Augmentation Evoker (1473): current Chronowarden/Scalecommander loop.
    { id="audit12_aug_fire_breath", spec=1473, spell="Fire Breath", name="Fire Breath release", moment="Release", event="EMPOWER_STOP", spellIDs={357208,382266}, cue="deepfire", preset="subtle", cooldown=1.5, defaultOn=true, defaultSounds={4553204,4569652}, defaultDelays={0,100}, description="Empowered Fire Breath release while Ebon Might is active." },
    { id="audit12_aug_tip_scales", spec=1473, spell="Tip the Scales", name="Tip the Scales", moment="Cast", event="SUCCEEDED", spellIDs={370553}, cue="major", preset="subtle", cooldown=3, defaultOn=true, defaultSounds={4686040,4558561}, defaultDelays={0,90}, description="Instant maximum-rank empower shortcut." },
    { id="audit12_aug_time_skip", spec=1473, spell="Time Skip", name="Time Skip", moment="Channeling", event="CHANNEL_START", spellIDs={404977}, capability="chronowarden", cue="bronze", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={4558551,4686040}, defaultDelays={0,100}, description="Chronowarden's two-second channel cooldown." },
    { id="audit12_aug_eruption", spec=1473, spell="Eruption", name="Eruption", moment="Cast", event="SUCCEEDED", spellIDs={395160}, cue="earth", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={4577695,4553587}, defaultDelays={0,90}, description="Two-and-a-half-second Essence spender cast." },
    { id="audit12_aug_living_flame", spec=1473, spell="Living Flame", name="Living Flame", moment="Cast", event="SUCCEEDED", spellIDs={361469}, cue="deepfire", preset="medium", cooldown=1.2, defaultOn=false, defaultSounds={4553204}, defaultDelays={0}, description="Two-second filler and Essence Burst generator." },
    { id="audit12_aug_azure_strike", spec=1473, spell="Azure Strike", name="Azure Strike", moment="Cast", event="SUCCEEDED", spellIDs={362969}, cue="arcane", preset="medium", cooldown=1.2, defaultOn=false, defaultSounds={4558551}, defaultDelays={0}, description="Instant movement filler." },
    { id="audit12_aug_blistering_scales", spec=1473, spell="Blistering Scales", name="Blistering Scales", moment="Cast", event="SUCCEEDED", spellIDs={360827}, cue="earth", preset="subtle", cooldown=1.5, defaultOn=true, defaultSounds={4577695,4553587}, defaultDelays={0,90}, description="Instant tank support buff." },
    { id="audit12_aug_hover", spec=1473, spell="Hover", name="Hover", moment="Cast", event="SUCCEEDED", spellIDs={358267}, cue="draconic", preset="subtle", cooldown=1.5, defaultOn=false, defaultSounds={4555731}, defaultDelays={0}, description="Instant movement/casting utility." },
    { id="audit12_aug_mass_eruption", spec=1473, spell="Mass Eruption", name="Mass Eruption", moment="Cast", event="SUCCEEDED", spellIDs={438587}, capability="scalecommander", cue="earth", preset="subtle", cooldown=1.5, defaultOn=true, defaultSounds={4577695,4553587}, defaultDelays={0,100}, description="Scalecommander AoE spender talent." },

    -- Havoc Demon Hunter (577): important buttons across both hero builds.
    { id="audit12_hav_reavers_glaive", spec=577, spell="Reaver's Glaive", name="Reaver's Glaive", moment="Cast", event="SUCCEEDED", spellIDs={442294}, capability="dh_aldrachi", cue="fel", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={568902,568281}, defaultDelays={0,90}, description="Aldrachi Reaver's current rotational glaive." },
    { id="audit12_hav_annihilation", spec=577, spell="Annihilation", name="Annihilation", moment="Cast", event="SUCCEEDED", spellIDs={201427}, cue="fel", preset="medium", cooldown=0.9, defaultOn=true, defaultSounds={568281}, defaultDelays={0}, description="Metamorphosis spender replacement." },
    { id="audit12_hav_death_sweep", spec=577, spell="Death Sweep", name="Death Sweep", moment="Cast", event="SUCCEEDED", spellIDs={210152}, cue="fel", preset="medium", cooldown=1.0, defaultOn=true, defaultSounds={568902}, defaultDelays={0}, description="Metamorphosis Blade Dance replacement." },
    { id="audit12_hav_blade_dance", spec=577, spell="Blade Dance", name="Blade Dance", moment="Cast", event="SUCCEEDED", spellIDs={188499}, cue="fel", preset="medium", cooldown=1.0, defaultOn=true, defaultSounds={568902,568281}, defaultDelays={0,70}, description="Core short-cooldown rotational button." },
    { id="audit12_hav_chaos_strike", spec=577, spell="Chaos Strike", name="Chaos Strike", moment="Cast", event="SUCCEEDED", spellIDs={162794}, cue="fel", preset="medium", cooldown=0.9, defaultOn=false, defaultSounds={568281}, defaultDelays={0}, description="Fury spender; optional to avoid frequent strike spam." },
    { id="audit12_hav_essence_break", spec=577, spell="Essence Break", name="Essence Break", moment="Cast", event="SUCCEEDED", spellIDs={258860}, cue="fel", preset="subtle", cooldown=1.5, defaultOn=true, defaultSounds={1455091,568281}, defaultDelays={0,90}, description="Burst-window instant debuff and strike." },
    { id="audit12_hav_felblade", spec=577, spell="Felblade", name="Felblade", moment="Cast", event="SUCCEEDED", spellIDs={213241}, cue="fel", preset="medium", cooldown=1.0, defaultOn=false, defaultSounds={568902}, defaultDelays={0}, description="Instant Fury generator/talent button." },
    { id="audit12_hav_immolation_aura", spec=577, spell="Immolation Aura", name="Immolation Aura", moment="Cast", event="SUCCEEDED", spellIDs={258920}, cue="fel", preset="medium", cooldown=1.0, defaultOn=true, defaultSounds={568902,568281}, defaultDelays={0,80}, description="Short cooldown Fury generator." },
    { id="audit12_hav_vengeful_retreat", spec=577, spell="Vengeful Retreat", name="Vengeful Retreat", moment="Cast", event="SUCCEEDED", spellIDs={198793}, cue="fel", preset="subtle", cooldown=1.5, defaultOn=false, defaultSounds={903900,568123}, defaultDelays={0,80}, description="Instant Exergy/Initiative setup movement." },
    { id="audit12_hav_fel_rush", spec=577, spell="Fel Rush", name="Fel Rush", moment="Cast", event="SUCCEEDED", spellIDs={195072}, cue="fel", preset="subtle", cooldown=1.2, defaultOn=false, defaultSounds={903900}, defaultDelays={0}, description="Instant movement filler." },

    -- Vengeance Demon Hunter (581): builder/spender and defensive coverage.
    { id="audit12_ven_infernal_strike", spec=581, spell="Infernal Strike", name="Infernal Strike", moment="Cast", event="SUCCEEDED", spellIDs={189110}, cue="fel", preset="subtle", cooldown=1.2, defaultOn=true, defaultSounds={903900,568902}, defaultDelays={0,80}, description="Instant off-GCD movement/charge." },
    { id="audit12_ven_fracture", spec=581, spell="Fracture", name="Fracture", moment="Cast", event="SUCCEEDED", spellIDs={263642}, cue="fel", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={568281}, defaultDelays={0}, description="Core instant Fury and Soul Fragment generator." },
    { id="audit12_ven_spirit_bomb", spec=581, spell="Spirit Bomb", name="Spirit Bomb", moment="Cast", event="SUCCEEDED", spellIDs={247454}, cue="fel", preset="medium", cooldown=0.9, defaultOn=true, defaultSounds={1455091,568281}, defaultDelays={0,80}, description="Core instant Soul spender." },
    { id="audit12_ven_soul_cleave", spec=581, spell="Soul Cleave", name="Soul Cleave", moment="Cast", event="SUCCEEDED", spellIDs={228477}, cue="fel", preset="medium", cooldown=0.9, defaultOn=true, defaultSounds={568281}, defaultDelays={0}, description="Core instant fallback Soul spender." },
    { id="audit12_ven_immolation_aura", spec=581, spell="Immolation Aura", name="Immolation Aura", moment="Cast", event="SUCCEEDED", spellIDs={258920}, cue="fel", preset="medium", cooldown=1.0, defaultOn=true, defaultSounds={568902,568281}, defaultDelays={0,80}, description="Instant Fury generator." },
    { id="audit12_ven_sigil_flame", spec=581, spell="Sigil of Flame", name="Sigil of Flame", moment="Cast", event="SUCCEEDED", spellIDs={204596}, cue="fel", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={1360219}, defaultDelays={0}, description="Instant ground-sigil generator." },
    { id="audit12_ven_sigil_spite", spec=581, spell="Sigil of Spite", name="Sigil of Spite", moment="Cast", event="SUCCEEDED", spellIDs={390163}, cue="fel", preset="subtle", cooldown=2.0, defaultOn=true, defaultSounds={1455091,568281}, defaultDelays={0,90}, description="Instant offensive sigil talent." },
    { id="audit12_ven_felblade", spec=581, spell="Felblade", name="Felblade", moment="Cast", event="SUCCEEDED", spellIDs={232893}, cue="fel", preset="medium", cooldown=1.0, defaultOn=false, defaultSounds={568902}, defaultDelays={0}, description="Instant Fury generator talent." },
    { id="audit12_ven_demon_spikes", spec=581, spell="Demon Spikes", name="Demon Spikes", moment="Cast", event="SUCCEEDED", spellIDs={203720}, cue="fel", preset="subtle", cooldown=2.0, defaultOn=true, defaultSounds={568123,568281}, defaultDelays={0,100}, description="Instant primary active defensive." },
    { id="audit12_ven_darkness", spec=581, spell="Darkness", name="Darkness", moment="Cast", event="SUCCEEDED", spellIDs={196718}, cue="fel", preset="subtle", cooldown=4.0, defaultOn=true, defaultSounds={568123,5259954}, defaultDelays={0,100}, description="Instant group defensive cooldown." },

    -- Devourer Demon Hunter (1480): outside/inside Void Metamorphosis.
    { id="audit12_devourer_reap", spec=1480, spell="Reap", name="Reap", moment="Cast", event="SUCCEEDED", spellIDs={1226019}, cue="void", preset="medium", cooldown=0.9, defaultOn=true, defaultSounds={5917414,6995073}, defaultDelays={0,80}, description="Instant soul collector outside Void Metamorphosis." },
    { id="audit12_devourer_consume", spec=1480, spell="Consume", name="Consume", moment="Cast", event="SUCCEEDED", spellIDs={473662}, cue="void", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={568751,5342340}, defaultDelays={0,80}, description="Current two-second outside-form cast; replaces the stale passive ID." },
    { id="audit12_devourer_soul_immolation", spec=1480, spell="Soul Immolation", name="Soul Immolation", moment="Cast", event="SUCCEEDED", spellIDs={1241937}, cue="void", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={5342340,5141255}, defaultDelays={0,80}, description="Instant setup cast for Soulburst windows." },
    { id="audit12_devourer_voidblade", spec=1480, spell="Voidblade", name="Voidblade", moment="Cast", event="SUCCEEDED", spellIDs={1245412}, cue="void", preset="medium", cooldown=0.9, defaultOn=true, defaultSounds={5917414,6022528}, defaultDelays={0,70}, description="Instant melee setup and Voidrush interaction." },
    { id="audit12_devourer_hunt", spec=1480, spell="The Hunt", name="The Hunt", moment="Cast", event="SUCCEEDED", spellIDs={1246167}, cue="void", preset="subtle", cooldown=2.0, defaultOn=true, defaultSounds={6907105,903900}, defaultDelays={0,90}, description="Current one-second cast; supports Huggling into Void Meta." },
    { id="audit12_devourer_hungering_slash", spec=1480, spell="Hungering Slash", name="Hungering Slash", moment="Cast", event="SUCCEEDED", spellIDs={1239519}, cue="void", preset="medium", cooldown=1.0, defaultOn=true, defaultSounds={6995073}, defaultDelays={0}, description="Instant outside-form proc setup and Reaper's Toll smuggling." },
    { id="audit12_devourer_devour", spec=1480, spell="Devour", name="Devour", moment="Cast", event="SUCCEEDED", spellIDs={1217610}, cue="void", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={568751,5342340}, defaultDelays={0,80}, description="Current 1.5-second Void Metamorphosis upgrade." },
    { id="audit12_devourer_cull", spec=1480, spell="Cull", name="Cull", moment="Cast", event="SUCCEEDED", spellIDs={1245453}, cue="void", preset="medium", cooldown=1.0, defaultOn=true, defaultSounds={5917414,1664264}, defaultDelays={0,80}, description="Instant Reap upgrade inside Void Metamorphosis." },
    { id="audit12_devourer_reapers_toll", spec=1480, spell="Reaper's Toll", name="Reaper's Toll", moment="Cast", event="SUCCEEDED", spellIDs={1245470}, cue="void", preset="medium", cooldown=1.0, defaultOn=true, defaultSounds={6982611,568751}, defaultDelays={0,80}, description="Instant Hungering Slash upgrade inside Void Metamorphosis." },
    { id="audit12_devourer_pierce_veil", spec=1480, spell="Pierce the Veil", name="Pierce the Veil", moment="Cast", event="SUCCEEDED", spellIDs={1245483}, cue="void", preset="medium", cooldown=1.0, defaultOn=true, defaultSounds={5917414,6022528}, defaultDelays={0,70}, description="Instant Voidblade upgrade inside Void Metamorphosis." },
    { id="audit12_devourer_predator_wake", spec=1480, spell="Predator's Wake", name="Predator's Wake", moment="Cast", event="SUCCEEDED", spellIDs={1259431}, cue="void", preset="medium", cooldown=1.5, defaultOn=true, defaultSounds={6908118,5141255}, defaultDelays={0,90}, description="Instant Hunt upgrade inside Void Metamorphosis." },
}

for _, rule in ipairs(rules) do
    ns.AdditionalSpecRules[#ns.AdditionalSpecRules + 1] = rule
end
