local _, ns = ...

-- Midnight 12.1 first pass.  These are deliberately player-originated casts,
-- channels, or verified player auras: pet/projectile-only effects stay out
-- until Core can optionally route combat-log spell events.
ns.AdditionalCapabilityGroups = ns.AdditionalCapabilityGroups or {}

ns.AdditionalCapabilityGroups.priest_archon = { 449806, 453799, 453845, 454001 }
ns.AdditionalCapabilityGroups.priest_oracle = { 428924 }
ns.AdditionalCapabilityGroups.priest_voidweaver = { 447444, 448403, 449880, 450405 }
ns.AdditionalCapabilityGroups.priest_master_darkness = { 1253590, 1253827, 1253845 }
ns.AdditionalCapabilityGroups.fired_up = { 1257348, 1257349 }
ns.AdditionalCapabilityGroups.priest_benediction = { 1262755, 1262758, 1262760 }
ns.AdditionalCapabilityGroups.priest_void_apparitions = { 1264096, 1264104, 1264107 }
ns.AdditionalCapabilityGroups.warlock_hellcaller = { 442726, 445465, 445468 }
ns.AdditionalCapabilityGroups.warlock_diabolist = { 428911, 429115, 429130, 429917 }
ns.AdditionalCapabilityGroups.warlock_soul_harvester = { 387016, 449614, 449638, 449703, 449704 }
ns.AdditionalCapabilityGroups.warlock_shadow_nathreza = { 1261984, 1261990 }
ns.AdditionalCapabilityGroups.warlock_dominion_argus = { 1276163, 1276190, 1276222 }
ns.AdditionalCapabilityGroups.warlock_embers_nihilam = { 1265770, 1265772, 1265774 }

local rules = {
    -- Fire Mage: one release, two major visual signatures, and only the two
    -- player-state moments that can be distinguished without spell spam.
    { id="fire_pyroblast", spec=63, spell="Pyroblast", moment="Release", event="SUCCEEDED", spellIDs={11366}, preset="medium", cooldown=0.8, defaultOn=true,
      defaultSounds={1392377}, defaultDelays={0}, description="A bright impact for each committed Pyroblast." },
    { id="fire_combustion", spec=63, spell="Combustion", moment="Cast", event="SUCCEEDED", spellIDs={190319}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={1390656,4573332}, defaultDelays={0,70}, description="A short ignition phrase for the burst window." },
    { id="fire_meteor", spec=63, spell="Meteor", moment="Cast", event="SUCCEEDED", spellIDs={153561}, preset="subtle", cooldown=2, defaultOn=true,
      defaultSounds={568024,4573332}, defaultDelays={0,110}, description="A deep descending impact; its damage ticks remain silent." },
    { id="fire_frostfire_bolt", spec=63, spell="Frostfire Bolt", moment="Cast", event="SUCCEEDED", spellIDs={431044}, capability="frostfire", preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={1631379,1685531}, defaultDelays={0,55}, description="Frostfire-only: a cool bolt with a small flame tail." },
    { id="fire_fire_blast", spec=63, spell="Fire Blast", moment="Cast", event="SUCCEEDED", spellIDs={319836}, preset="expressive", cooldown=0.8, defaultOn=false,
      defaultSounds={568023}, defaultDelays={0}, description="Optional instant Hot Streak builder; disabled by default to avoid frequent accents." },
    { id="fire_fireball", spec=63, spell="Fireball", moment="Cast", event="SUCCEEDED", spellIDs={133}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={568951}, defaultDelays={0}, description="Optional hard-cast filler accent." },
    { id="fire_scorch", spec=63, spell="Scorch", moment="Cast", event="SUCCEEDED", spellIDs={2948}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={568023}, defaultDelays={0}, description="Optional movement filler accent; Scorch is instant." },
    { id="fire_flamestrike", spec=63, spell="Flamestrike", moment="Release", event="SUCCEEDED", spellIDs={2120}, preset="medium", cooldown=1.2, defaultOn=true,
      defaultSounds={568024,4573332}, defaultDelays={0,70}, description="A compact area-fire release for the current AoE rotation." },

    -- Discipline Priest
    { id="disc_penance", spec=256, spell="Penance", moment="Channel", event="CHANNEL_START", spellIDs={47540}, preset="medium", cooldown=1.2, defaultOn=true,
      defaultSounds={1708148}, defaultDelays={0}, description="One cast accent; individual bolts stay silent." },
    { id="disc_radiance", spec=256, spell="Power Word: Radiance", moment="Cast", event="SUCCEEDED", spellIDs={194509}, preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={1709039}, defaultDelays={0}, description="A focused burst of group radiance." },
    { id="disc_evangelism", spec=256, spell="Evangelism", moment="Cast", event="SUCCEEDED", spellIDs={472433}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={5207969,5205686}, defaultDelays={0,90}, description="A measured punctuation for the Atonement window." },
    { id="disc_ultimate_penitence", spec=256, spell="Ultimate Penitence", moment="Channel", event="CHANNEL_START", spellIDs={421453}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={1708148,5205686}, defaultDelays={0,100}, description="One solemn channel opening, never its ticks." },
    { id="disc_void_blast", spec=256, spell="Void Blast", moment="Cast", event="SUCCEEDED", spellIDs={450405}, capability="priest_voidweaver", preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={1714480,5342340}, defaultDelays={0,70}, description="Voidweaver: the transformed Smite lands with a restrained void pulse." },
    { id="disc_void_shield", spec=256, spell="Void Shield (Apex)", moment="Cast", event="SUCCEEDED", spellIDs={280749}, capability="priest_master_darkness", preset="subtle", cooldown=3, defaultOn=true,
      defaultSounds={1708158,5342340}, defaultDelays={0,80}, description="Apex: the upgraded Power Word: Shield is given one void-lit accent." },
    { id="disc_power_word_shield", spec=256, spell="Power Word: Shield", moment="Cast", event="SUCCEEDED", spellIDs={17}, preset="medium", cooldown=0.8, defaultOn=true,
      defaultSounds={1708158}, defaultDelays={0}, description="A focused shield application for Atonement ramps." },
    { id="disc_flash_heal", spec=256, spell="Flash Heal", moment="Cast", event="SUCCEEDED", spellIDs={2061}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={1709039}, defaultDelays={0}, description="Optional emergency heal accent." },
    { id="disc_mind_blast", spec=256, spell="Mind Blast", moment="Cast", event="SUCCEEDED", spellIDs={8092}, preset="expressive", cooldown=1.1, defaultOn=false,
      defaultSounds={1714480}, defaultDelays={0}, description="Optional rotational damage accent for Atonement ramps." },
    { id="disc_shadow_word_death", spec=256, spell="Shadow Word: Death", moment="Release", event="SUCCEEDED", spellIDs={32379}, preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={568184}, defaultDelays={0}, description="A restrained execute-window release." },
    { id="disc_smite", spec=256, spell="Smite", moment="Cast", event="SUCCEEDED", spellIDs={585}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={1708148}, defaultDelays={0}, description="Optional filler damage accent; disabled by default." },
    { id="disc_archangel", spec=256, spell="Archangel", moment="Cast", event="SUCCEEDED", spellIDs={197862}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={5207969,5205686}, defaultDelays={0,90}, description="A major Atonement-window lift." },
    { id="disc_mindbender", spec=256, spell="Mindbender", moment="Cast", event="SUCCEEDED", spellIDs={1280137}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={1717716,5342340}, defaultDelays={0,90}, description="A concise shadow summon for the healing window." },
    { id="disc_power_word_barrier", spec=256, spell="Power Word: Barrier", moment="Cast", event="SUCCEEDED", spellIDs={62618}, preset="subtle", cooldown=5, defaultOn=true,
      defaultSounds={5207969,5205686}, defaultDelays={0,100}, description="A major defensive declaration." },

    -- Holy Priest
    { id="holy_serenity", spec=257, spell="Holy Word: Serenity", moment="Cast", event="SUCCEEDED", spellIDs={2050}, preset="medium", cooldown=0.8, defaultOn=true,
      defaultSounds={1698678}, defaultDelays={0}, description="A clear single-target holy release." },
    { id="holy_sanctify", spec=257, spell="Holy Word: Sanctify", moment="Cast", event="SUCCEEDED", spellIDs={34861}, preset="medium", cooldown=1, defaultOn=true,
      defaultSounds={1698676}, defaultDelays={0}, description="A compact sanctuary bloom." },
    { id="holy_hymn", spec=257, spell="Divine Hymn", moment="Channel", event="CHANNEL_START", spellIDs={64843}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={1698674,5205686}, defaultDelays={0,120}, description="One ceremonial opening; the hymn itself remains Blizzard audio." },
    { id="holy_apotheosis", spec=257, spell="Apotheosis", moment="Cast", event="SUCCEEDED", spellIDs={200183}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={1698671,5205686}, defaultDelays={0,90}, description="A luminous major-cooldown lift." },
    { id="holy_archon_halo", spec=257, spell="Halo", moment="Cast", event="SUCCEEDED", spellIDs={120517}, capability="priest_archon", preset="subtle", cooldown=2, defaultOn=true,
      defaultSounds={567985,5259954}, defaultDelays={0,70}, description="Archon-only: a radiant ring beginning its outward sweep." },
    { id="holy_chastise", spec=257, spell="Holy Word: Chastise", moment="Release", event="SUCCEEDED", spellIDs={88625}, preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={567985}, defaultDelays={0}, description="A measured holy damage release that also drives Divine Image." },
    { id="holy_prayer_of_mending", spec=257, spell="Prayer of Mending", moment="Cast", event="SUCCEEDED", spellIDs={33076}, preset="medium", cooldown=0.9, defaultOn=true,
      defaultSounds={1698678}, defaultDelays={0}, description="A light, single-cast healing bounce accent." },
    { id="holy_prayer_of_healing", spec=257, spell="Prayer of Healing", moment="Cast", event="SUCCEEDED", spellIDs={596}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={1698676}, defaultDelays={0}, description="Optional group-heal cast accent." },
    { id="holy_flash_heal", spec=257, spell="Flash Heal", moment="Cast", event="SUCCEEDED", spellIDs={2061}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={1698678}, defaultDelays={0}, description="Optional emergency-heal cast accent." },
    { id="holy_holy_fire", spec=257, spell="Holy Fire", moment="Cast", event="SUCCEEDED", spellIDs={14914}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={567985}, defaultDelays={0}, description="Optional damage filler accent." },
    { id="holy_guardian_spirit", spec=257, spell="Guardian Spirit", moment="Cast", event="SUCCEEDED", spellIDs={47788}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={5207969,5205686}, defaultDelays={0,100}, description="A major protective cooldown." },
    { id="holy_power_infusion", spec=257, spell="Power Infusion", moment="Cast", event="SUCCEEDED", spellIDs={10060}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={5207969,5259954}, defaultDelays={0,90}, description="A short support cooldown declaration." },

    -- Shadow Priest
    { id="shadow_voidform", spec=258, spell="Voidform", moment="Cast", event="SUCCEEDED", spellIDs={228264}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={1717716,5342340}, defaultDelays={0,100}, description="A deep opening for Voidform." },
    { id="shadow_void_torrent", spec=258, spell="Void Torrent", moment="Channel", event="CHANNEL_START", spellIDs={263165}, preset="subtle", cooldown=3, defaultOn=true,
      defaultSounds={568751,1716507}, defaultDelays={0,80}, description="One void-channel opening; no added beam loop." },
    { id="shadow_tentacle_slam", spec=258, spell="Tentacle Slam", moment="Cast", event="SUCCEEDED", spellIDs={1227280}, preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={5342340}, defaultDelays={0}, description="A low Old God punctuation for the new cleave spell." },
    { id="shadow_void_blast", spec=258, spell="Void Blast", moment="Cast", event="SUCCEEDED", spellIDs={450405}, capability="priest_voidweaver", preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={1714480,5342340}, defaultDelays={0,70}, description="Voidweaver: transformed Mind Blast with a tight void impact." },
    { id="shadow_archon_halo", spec=258, spell="Halo", moment="Cast", event="SUCCEEDED", spellIDs={120644}, capability="priest_archon", preset="subtle", cooldown=2, defaultOn=true,
      defaultSounds={567985,5259954}, defaultDelays={0,70}, description="Archon-only: a bright halo release over the void kit." },
    { id="shadow_vampiric_touch", spec=258, spell="Vampiric Touch", moment="Cast", event="SUCCEEDED", spellIDs={34914}, preset="medium", cooldown=0.8, defaultOn=true,
      defaultSounds={568984}, defaultDelays={0}, description="A restrained shadow DoT application." },
    { id="shadow_shadow_word_pain", spec=258, spell="Shadow Word: Pain", moment="Cast", event="SUCCEEDED", spellIDs={589}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={568040}, defaultDelays={0}, description="Optional spread-DoT accent; disabled by default." },
    { id="shadow_shadow_word_madness", spec=258, spell="Shadow Word: Madness", moment="Release", event="SUCCEEDED", spellIDs={335467}, preset="medium", cooldown=0.9, defaultOn=true,
      defaultSounds={568184,5342340}, defaultDelays={0,70}, description="A focused Insanity spender release." },
    { id="shadow_void_volley", spec=258, spell="Void Volley", moment="Cast", event="SUCCEEDED", spellIDs={1240401}, preset="medium", cooldown=1.2, defaultOn=true,
      defaultSounds={5342340}, defaultDelays={0}, description="A short void volley used to open and sustain Voidform windows." },
    { id="shadow_mind_blast", spec=258, spell="Mind Blast", moment="Cast", event="SUCCEEDED", spellIDs={8092}, preset="expressive", cooldown=1.1, defaultOn=false,
      defaultSounds={1714480}, defaultDelays={0}, description="Optional rotational Insanity generator accent." },
    { id="shadow_shadow_word_death", spec=258, spell="Shadow Word: Death", moment="Release", event="SUCCEEDED", spellIDs={32379}, preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={568184}, defaultDelays={0}, description="A compact execute-window release." },
    { id="shadow_shadowfiend", spec=258, spell="Shadowfiend", moment="Cast", event="SUCCEEDED", spellIDs={34433}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={568751,5342340}, defaultDelays={0,100}, description="A major shadow summon for the burst window." },

    -- Affliction Warlock
    { id="aff_haunt", spec=265, spell="Haunt", moment="Cast", event="SUCCEEDED", spellIDs={48181}, preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={2068359,568984}, defaultDelays={0,65}, description="A single hungry shadow release." },
    { id="aff_unstable_affliction", spec=265, spell="Unstable Affliction", moment="Cast", event="SUCCEEDED", spellIDs={316099}, preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={2068359}, defaultDelays={0}, description="A concise curse application; damage-over-time ticks stay silent." },
    { id="aff_seed", spec=265, spell="Seed of Corruption", moment="Cast", event="SUCCEEDED", spellIDs={27243}, preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={2068305}, defaultDelays={0}, description="A dark seed planted without reacting to its detonation." },
    { id="aff_darkglare", spec=265, spell="Summon Darkglare", moment="Cast", event="SUCCEEDED", spellIDs={205180}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={568751,5342340}, defaultDelays={0,100}, description="A heavy void summons accent." },
    { id="aff_malevolence", spec=265, spell="Malevolence", moment="Cast", event="SUCCEEDED", spellIDs={430014}, capability="warlock_hellcaller", preset="subtle", cooldown=3, defaultOn=true,
      defaultSounds={568281,568123}, defaultDelays={0,85}, description="Hellcaller: a deliberate fel-shadow burst window." },
    { id="aff_agony", spec=265, spell="Agony", moment="Cast", event="SUCCEEDED", spellIDs={980}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={568984}, defaultDelays={0}, description="Optional primary DoT application accent; disabled by default for multi-target content." },
    { id="aff_corruption", spec=265, spell="Corruption", moment="Cast", event="SUCCEEDED", spellIDs={172}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={568984}, defaultDelays={0}, description="Optional DoT application accent." },
    { id="aff_wither", spec=265, spell="Wither", moment="Cast", event="SUCCEEDED", spellIDs={445465}, capability="warlock_hellcaller", preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={2101386,568984}, defaultDelays={0,65}, description="Hellcaller: the current Immolate replacement receives a dry shadow tail." },
    { id="aff_dark_harvest", spec=265, spell="Dark Harvest", moment="Cast", event="SUCCEEDED", spellIDs={1257052}, capability="warlock_soul_harvester", preset="subtle", cooldown=3, defaultOn=true,
      defaultSounds={568751,5342340}, defaultDelays={0,100}, description="Soul Harvester: the current periodic-damage harvest cooldown." },
    { id="aff_malefic_grasp", spec=265, spell="Malefic Grasp", moment="Cast", event="SUCCEEDED", spellIDs={1261149}, preset="expressive", cooldown=1.1, defaultOn=false,
      defaultSounds={2068359}, defaultDelays={0}, description="Optional channel-window damage accent." },
    { id="aff_drain_soul", spec=265, spell="Drain Soul", moment="Channel", event="CHANNEL_START", spellIDs={198590}, preset="expressive", cooldown=1.5, defaultOn=false,
      defaultSounds={568751}, defaultDelays={0}, description="Optional one-time filler-channel opening." },
    { id="aff_shadow_bolt", spec=265, spell="Shadow Bolt", moment="Cast", event="SUCCEEDED", spellIDs={232670}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={568406}, defaultDelays={0}, description="Optional filler cast accent." },
    -- Demonology Warlock
    { id="demo_hand_of_guldan", spec=266, spell="Hand of Gul'dan", moment="Cast", event="SUCCEEDED", spellIDs={105174}, preset="medium", cooldown=1, defaultOn=true,
      defaultSounds={2114932,568058}, defaultDelays={0,65}, description="A fel hand thrown into the demon swarm." },
    { id="demo_dreadstalkers", spec=266, spell="Call Dreadstalkers", moment="Cast", event="SUCCEEDED", spellIDs={104316}, preset="medium", cooldown=1.2, defaultOn=true,
      defaultSounds={2132136}, defaultDelays={0}, description="A short demonic call, not individual pet attacks." },
    { id="demo_tyrant", spec=266, spell="Summon Demonic Tyrant", moment="Cast", event="SUCCEEDED", spellIDs={265187}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={568123,568181}, defaultDelays={0,100}, description="A broad fel-nova entrance for the Tyrant window." },
    { id="demo_implosion", spec=266, spell="Implosion", moment="Cast", event="SUCCEEDED", spellIDs={196277}, preset="subtle", cooldown=1.5, defaultOn=true,
      defaultSounds={568181,568718}, defaultDelays={0,60}, description="One compressed fel detonation." },
    { id="demo_grimoire_imp_lord", spec=266, spell="Grimoire: Imp Lord", moment="Cast", event="SUCCEEDED", spellIDs={1276452}, capability="warlock_diabolist", preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={568123,568181}, defaultDelays={0,100}, description="Diabolist: a major demonic summon." },
    { id="demo_grimoire_fel_ravager", spec=266, spell="Grimoire: Fel Ravager", moment="Cast", event="SUCCEEDED", spellIDs={1276467}, capability="warlock_diabolist", preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={568123,568181}, defaultDelays={0,100}, description="Diabolist: a major fel summon." },
    { id="demo_doomguard", spec=266, spell="Summon Doomguard", moment="Cast", event="SUCCEEDED", spellIDs={1276672}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={568123,5342340}, defaultDelays={0,100}, description="A major demon summon for the current Demonology opener." },
    { id="demo_power_siphon", spec=266, spell="Power Siphon", moment="Cast", event="SUCCEEDED", spellIDs={264130}, preset="medium", cooldown=1.2, defaultOn=true,
      defaultSounds={2114932,568058}, defaultDelays={0,65}, description="A focused implosion setup accent." },
    { id="demo_demonbolt", spec=266, spell="Demonbolt", moment="Cast", event="SUCCEEDED", spellIDs={264178}, preset="expressive", cooldown=1.1, defaultOn=false,
      defaultSounds={568058}, defaultDelays={0}, description="Optional Demonic Core spender accent." },
    { id="demo_infernal_bolt", spec=266, spell="Infernal Bolt", moment="Cast", event="SUCCEEDED", spellIDs={433891}, preset="expressive", cooldown=1.1, defaultOn=false,
      defaultSounds={568181}, defaultDelays={0}, description="Optional current filler spender accent." },
    { id="demo_shadow_bolt", spec=266, spell="Shadow Bolt", moment="Cast", event="SUCCEEDED", spellIDs={686}, preset="expressive", cooldown=1.2, defaultOn=false,
      defaultSounds={568406}, defaultDelays={0}, description="Optional Soul Shard generator accent." },
    { id="demo_dominion_argus", spec=266, spell="Dominion of Argus (Apex)", moment="Cast", event="SUCCEEDED", spellIDs={1276163,1276190,1276222}, capability="warlock_dominion_argus", preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={568123,5342340}, defaultDelays={0,120}, description="Apex: the current Dominion of Argus demon release." },
    -- Destruction Warlock
    { id="dest_chaos_bolt", spec=267, spell="Chaos Bolt", moment="Release", event="SUCCEEDED", spellIDs={116858}, preset="medium", cooldown=1, defaultOn=true,
      defaultSounds={2068257,2068263}, defaultDelays={0,70}, description="A sharp Shadowflame release." },
    { id="dest_infernal", spec=267, spell="Summon Infernal", moment="Cast", event="SUCCEEDED", spellIDs={1122}, preset="subtle", cooldown=4, defaultOn=true,
      defaultSounds={2068356,2068353}, defaultDelays={0,130}, description="A meteor-sized infernal arrival." },
    { id="dest_rain_of_fire", spec=267, spell="Rain of Fire", moment="Cast", event="SUCCEEDED", spellIDs={1214467}, preset="medium", cooldown=1.2, defaultOn=true,
      defaultSounds={2114941}, defaultDelays={0}, description="One hellfire opening; the rain itself adds no loop." },
    { id="dest_cataclysm", spec=267, spell="Cataclysm", moment="Cast", event="SUCCEEDED", spellIDs={152108}, preset="subtle", cooldown=3, defaultOn=true,
      defaultSounds={2144923,2144927}, defaultDelays={0,100}, description="A deep, decisive Shadowflame collapse." },
    { id="dest_wither", spec=267, spell="Wither", moment="Cast", event="SUCCEEDED", spellIDs={445465}, capability="warlock_hellcaller", preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={2101386,568984}, defaultDelays={0,65}, description="Hellcaller: the Immolate replacement receives a dry shadow tail." },
    { id="dest_immolate", spec=267, spell="Immolate", moment="Cast", event="SUCCEEDED", spellIDs={348}, preset="medium", cooldown=1.1, defaultOn=true,
      defaultSounds={2101386,568984}, defaultDelays={0,65}, description="A deliberate fire DoT application." },
    { id="dest_conflagrate", spec=267, spell="Conflagrate", moment="Cast", event="SUCCEEDED", spellIDs={17962}, preset="expressive", cooldown=0.9, defaultOn=false,
      defaultSounds={2068257}, defaultDelays={0}, description="Optional instant shard-builder accent." },
    { id="dest_shadowburn", spec=267, spell="Shadowburn", moment="Release", event="SUCCEEDED", spellIDs={17877}, preset="medium", cooldown=0.9, defaultOn=true,
      defaultSounds={2068257,2068263}, defaultDelays={0,70}, description="A compact execute and shard-spend release." },
    { id="dest_soul_fire", spec=267, spell="Soul Fire", moment="Cast", event="SUCCEEDED", spellIDs={6353}, preset="medium", cooldown=1.2, defaultOn=true,
      defaultSounds={2068356,2068257}, defaultDelays={0,70}, description="A heavy current rotation cast." },
    { id="dest_channel_demonfire", spec=267, spell="Channel Demonfire", moment="Channel", event="CHANNEL_START", spellIDs={196447}, preset="subtle", cooldown=3, defaultOn=true,
      defaultSounds={2068356,2068353}, defaultDelays={0,100}, description="One channel opening; individual bolts remain silent." },
    { id="dest_havoc", spec=267, spell="Havoc", moment="Cast", event="SUCCEEDED", spellIDs={80240}, preset="subtle", cooldown=3, defaultOn=true,
      defaultSounds={2068305,2068257}, defaultDelays={0,80}, description="A focused cleave-window declaration." },
    { id="dest_malevolence", spec=267, spell="Malevolence", moment="Cast", event="SUCCEEDED", spellIDs={430014}, capability="warlock_hellcaller", preset="subtle", cooldown=3, defaultOn=true,
      defaultSounds={568281,568123}, defaultDelays={0,85}, description="Hellcaller: a deliberate fel-shadow burst window." },
}

ns.AdditionalSpecRules = ns.AdditionalSpecRules or {}
for _, rule in ipairs(rules) do
    ns.AdditionalSpecRules[#ns.AdditionalSpecRules + 1] = rule
end
