local _, ns = ...

-- This file is deliberately declarative.  Data.lua merges these rows after it
-- builds the base catalogue, so new specs do not need a second event router.
ns.AdditionalSpecRules = ns.AdditionalSpecRules or {}

local rules = {
    -- Augmentation Evoker: bronze support magic and direct player actions.
    { id="aug_ebon_might", spec=1473, spell="Ebon Might", moment="Cast", name="Ebon Might", event="SUCCEEDED", spellIDs={395152}, cue="bronze", preset="subtle", cooldown=2.5, defaultOn=true, defaultSounds={5141281,4558561}, defaultDelays={0,80}, description="A bronze pulse when your group buff is renewed." },
    { id="aug_prescience", spec=1473, spell="Prescience", moment="Cast", name="Prescience", event="SUCCEEDED", spellIDs={409311}, cue="bronze", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={4558551}, defaultDelays={0}, description="A small time-magic accent for Prescience." },
    { id="aug_breath_of_eons", spec=1473, spell="Breath of Eons", moment="Cast", name="Breath of Eons", event="SUCCEEDED", spellIDs={403631}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={4686040,4558551}, defaultDelays={0,120}, description="A decisive bronze wingbeat for your major cooldown." },
    { id="aug_upheaval_release", spec=1473, spell="Upheaval", moment="Release", name="Upheaval release", event="EMPOWER_STOP", spellIDs={396286,408092}, cue="earth", preset="subtle", cooldown=1.5, defaultOn=true, defaultSounds={4577695,4553587}, defaultDelays={0,100}, description="A grounded impact when Upheaval is released." },

    -- Druid
    { id="balance_starsurge", spec=102, spell="Starsurge", moment="Cast", name="Starsurge", event="SUCCEEDED", spellIDs={78674}, cue="arcane", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={1597454,1597457}, defaultDelays={0,90}, description="A compact astral release for Starsurge." },
    { id="balance_starfall", spec=102, spell="Starfall", moment="Cast", name="Starfall", event="SUCCEEDED", spellIDs={191034}, cue="arcane", preset="medium", cooldown=1.5, defaultOn=true, defaultSounds={568377}, defaultDelays={0}, description="One astral launch accent; Starfall's ticks stay silent." },
    { id="balance_celestial_alignment", spec=102, spell="Celestial Alignment", moment="Cast", name="Celestial Alignment", event="SUCCEEDED", spellIDs={194223,394013}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={1597431,5259954}, defaultDelays={0,130}, description="A bright astral opening for current Celestial Alignment or Incarnation." },
    { id="balance_moonfire_sunfire", spec=102, spell="Moonfire / Sunfire", moment="Cast", name="Moonfire / Sunfire", event="SUCCEEDED", spellIDs={8921,93402}, cue="nature", preset="expressive", cooldown=1.2, defaultOn=false, defaultSounds={1597438}, defaultDelays={0}, description="Optional soft DoT application accents." },
    { id="balance_force_of_nature", spec=102, spell="Force of Nature", moment="Cast", name="Force of Nature", event="SUCCEEDED", spellIDs={205636}, cue="nature", preset="medium", cooldown=2, defaultOn=true, defaultSounds={4556842}, defaultDelays={0}, description="A living pulse when the treants arrive." },
    { id="balance_fury_of_elune", spec=102, spell="Fury of Elune", moment="Cast", name="Fury of Elune", event="SUCCEEDED", spellIDs={202770}, cue="arcane", preset="medium", cooldown=2, defaultOn=true, defaultSounds={1417215,5259954}, defaultDelays={0,100}, description="A lunar surge for the talent cooldown." },
    { id="balance_convoke", spec=102, spell="Convoke the Spirits", moment="Channeling", name="Convoke the Spirits", event="CHANNEL_START", spellIDs={391528}, cue="nature", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={4556842,568377}, defaultDelays={0,100}, description="One verdant opening note for the channel." },
    { id="balance_wrath_starfire", spec=102, spell="Wrath / Starfire", moment="Cast", name="Wrath / Starfire", event="SUCCEEDED", spellIDs={5176,194153}, cue="arcane", preset="subtle", cooldown=1.2, defaultOn=false, defaultSounds={1597438}, defaultDelays={0}, description="Optional filler punctuation; live cast metadata controls Casting exposure." },

    { id="feral_feral_frenzy", spec=103, spell="Feral Frenzy", moment="Cast", name="Feral Frenzy", event="SUCCEEDED", spellIDs={274837}, cue="nature", preset="medium", cooldown=3, defaultOn=true, defaultSounds={4556842,568813}, defaultDelays={0,80}, description="A quick wind-and-dust flourish for Feral Frenzy." },
    { id="feral_berserk", spec=103, spell="Berserk", moment="Cast", name="Berserk", event="SUCCEEDED", spellIDs={106951,102543}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={4577695,4556844}, defaultDelays={0,120}, description="A primal surge for Berserk or Incarnation." },
    { id="feral_tigers_fury", spec=103, spell="Tiger's Fury", moment="Cast", name="Tiger's Fury", event="SUCCEEDED", spellIDs={5217}, cue="nature", preset="medium", cooldown=2, defaultOn=true, defaultSounds={4556842}, defaultDelays={0}, description="A compact primal surge for the energy cooldown." },
    { id="feral_rake_rip", spec=103, spell="Rake / Rip", moment="Cast", name="Rake / Rip", event="SUCCEEDED", spellIDs={1822,1079}, cue="nature", preset="expressive", cooldown=0.8, defaultOn=false, defaultSounds={568813}, defaultDelays={0}, description="Optional bleed punctuation." },
    { id="feral_shred", spec=103, spell="Shred", moment="Cast", name="Shred", event="SUCCEEDED", spellIDs={5221}, cue="nature", preset="expressive", cooldown=0.8, defaultOn=false, defaultSounds={4556842}, defaultDelays={0}, description="Optional single-target filler punctuation." },
    { id="feral_ferocious_bite", spec=103, spell="Ferocious Bite", moment="Cast", name="Ferocious Bite", event="SUCCEEDED", spellIDs={22568}, cue="nature", preset="medium", cooldown=1, defaultOn=true, defaultSounds={568813}, defaultDelays={0}, description="A clean finisher accent." },
    { id="feral_convoke", spec=103, spell="Convoke the Spirits", moment="Channeling", name="Convoke the Spirits", event="CHANNEL_START", spellIDs={391528}, cue="nature", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={4556842,568377}, defaultDelays={0,100}, description="One verdant opening note for the channel." },

    { id="guardian_rage_of_the_sleeper", spec=104, spell="Rage of the Sleeper", moment="Cast", name="Rage of the Sleeper", event="SUCCEEDED", spellIDs={200851}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={4577695,4553591}, defaultDelays={0,120}, description="A heavy stone surge for Rage of the Sleeper." },
    { id="guardian_berserk", spec=104, spell="Berserk", moment="Cast", name="Berserk", event="SUCCEEDED", spellIDs={106951,394786}, cue="earth", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={4556549,4553587}, defaultDelays={0,100}, description="An earthen growl for current Berserk or Incarnation." },
    { id="guardian_lunar_beam", spec=104, spell="Lunar Beam", moment="Cast", name="Lunar Beam", event="SUCCEEDED", spellIDs={204066}, cue="arcane", preset="medium", cooldown=2, defaultOn=true, defaultSounds={1417215,5259954}, defaultDelays={0,100}, description="A focused lunar descent for Lunar Beam." },
    { id="guardian_mangle_thrash", spec=104, spell="Mangle / Thrash", moment="Cast", name="Mangle / Thrash", event="SUCCEEDED", spellIDs={231064,77758}, cue="earth", preset="expressive", cooldown=0.8, defaultOn=false, defaultSounds={4553587}, defaultDelays={0}, description="Optional core bear-builder punctuation." },
    { id="guardian_raze", spec=104, spell="Raze", moment="Cast", name="Raze", event="SUCCEEDED", spellIDs={400254}, cue="earth", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={4553587,568813}, defaultDelays={0,80}, description="A heavy spender when Raze is talented." },
    { id="guardian_ironfur", spec=104, spell="Ironfur", moment="Cast", name="Ironfur", event="SUCCEEDED", spellIDs={192081}, cue="earth", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={4553587}, defaultDelays={0}, description="A restrained mitigation cue." },
    { id="guardian_frenzied_regeneration", spec=104, spell="Frenzied Regeneration", moment="Cast", name="Frenzied Regeneration", event="SUCCEEDED", spellIDs={22842}, cue="nature", preset="medium", cooldown=1, defaultOn=true, defaultSounds={4556842}, defaultDelays={0}, description="A brief restorative bear pulse." },
    { id="guardian_convoke", spec=104, spell="Convoke the Spirits", moment="Channeling", name="Convoke the Spirits", event="CHANNEL_START", spellIDs={391528}, cue="nature", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={4556842,568377}, defaultDelays={0,100}, description="One verdant opening note for the channel." },

    { id="resto_druid_wild_growth", spec=105, spell="Wild Growth", moment="Cast", name="Wild Growth", event="SUCCEEDED", spellIDs={48438}, cue="nature", preset="medium", cooldown=1, defaultOn=true, defaultSounds={1687858,1687861}, defaultDelays={0,80}, description="A living bloom when Wild Growth spreads." },
    { id="resto_druid_flourish", spec=105, spell="Flourish", moment="Cast", name="Flourish", event="SUCCEEDED", spellIDs={197721}, cue="major", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={1694578,1694579}, defaultDelays={0,100}, description="A broad verdant flourish for your HoT extension." },
    { id="resto_druid_tranquility", spec=105, spell="Tranquility", moment="Channeling", name="Tranquility", event="CHANNEL_START", spellIDs={740}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={568379}, defaultDelays={0}, description="One calm opening note when Tranquility begins." },
    { id="resto_druid_swiftmend", spec=105, spell="Swiftmend", moment="Cast", name="Swiftmend", event="SUCCEEDED", spellIDs={18562}, cue="nature", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={1687855}, defaultDelays={0}, description="A quick restorative accent for Swiftmend." },
    { id="resto_druid_lifebloom_rejuvenation", spec=105, spell="Lifebloom / Rejuvenation", moment="Cast", name="Lifebloom / Rejuvenation", event="SUCCEEDED", spellIDs={33763,774}, cue="nature", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={1687855,1597438}, defaultDelays={0,80}, description="Core HoT application accents." },
    { id="resto_druid_efflorescence", spec=105, spell="Efflorescence", moment="Cast", name="Efflorescence", event="SUCCEEDED", spellIDs={145205}, cue="nature", preset="medium", cooldown=1, defaultOn=true, defaultSounds={1687858}, defaultDelays={0}, description="A living ground-bloom accent." },
    { id="resto_druid_cooldowns", spec=105, spell="Ironbark / Incarnation", moment="Cast", name="Ironbark / Incarnation", event="SUCCEEDED", spellIDs={102342,33891}, cue="major", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={1694578,5259954}, defaultDelays={0,100}, description="Major defensive or Tree of Life opening." },
    { id="resto_druid_convoke", spec=105, spell="Convoke the Spirits", moment="Channeling", name="Convoke the Spirits", event="CHANNEL_START", spellIDs={391528}, cue="nature", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={4556842,568377}, defaultDelays={0,100}, description="One verdant opening note for the channel." },

    -- Shaman
    { id="ele_lava_burst", spec=262, spell="Lava Burst", moment="Cast", name="Lava Burst", event="SUCCEEDED", spellIDs={51505}, cue="deepfire", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={1100351,1100352}, defaultDelays={0,90}, description="A hot elemental punctuation for Lava Burst." },
    { id="ele_earth_shock", spec=262, spell="Earth Shock", moment="Cast", name="Earth Shock", event="SUCCEEDED", spellIDs={8042}, cue="earth", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={2576266,2576255}, defaultDelays={0,80}, description="A short earthen impact for Earth Shock." },
    { id="ele_stormkeeper", spec=262, spell="Stormkeeper / Fire Elemental", moment="Cast", name="Stormkeeper / Fire Elemental", event="SUCCEEDED", spellIDs={191634,198067}, cue="major", preset="subtle", cooldown=3, defaultOn=true, defaultSounds={1369107,1715016}, defaultDelays={0,120}, description="Major elemental cooldown variants." },
    { id="ele_ascendance", spec=262, spell="Ascendance", moment="Cast", name="Ascendance", event="SUCCEEDED", spellIDs={114050}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={1369107,5259954}, defaultDelays={0,120}, description="An elemental rise for Ascendance." },
    { id="ele_lightning_chain", spec=262, spell="Lightning Bolt / Chain Lightning", moment="Cast", name="Lightning Bolt / Chain Lightning", event="SUCCEEDED", spellIDs={188196,188443}, cue="air", preset="subtle", cooldown=0.8, defaultOn=false, defaultSounds={1369104}, defaultDelays={0}, description="Optional filler punctuation; current cast metadata controls Casting exposure." },
    { id="ele_flame_shock", spec=262, spell="Flame Shock", moment="Cast", name="Flame Shock", event="SUCCEEDED", spellIDs={188389}, cue="deepfire", preset="expressive", cooldown=0.8, defaultOn=false, defaultSounds={1100351}, defaultDelays={0}, description="Optional instant DoT application accent." },
    { id="ele_elemental_blast", spec=262, spell="Elemental Blast", moment="Cast", name="Elemental Blast", event="SUCCEEDED", spellIDs={117014}, cue="deepfire", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={1100351,1100352}, defaultDelays={0,90}, description="A concentrated elemental spender when talented." },
    { id="ele_tempest", spec=262, spell="Tempest", moment="Cast", name="Tempest", event="SUCCEEDED", spellIDs={454009}, cue="air", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={1369104,1715016}, defaultDelays={0,90}, description="A storm release for the current Tempest action." },

    { id="enh_crash_lightning", spec=263, spell="Crash Lightning", moment="Cast", name="Crash Lightning", event="SUCCEEDED", spellIDs={187874}, cue="air", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={1369104,1715016}, defaultDelays={0,80}, description="A single storm crack for Crash Lightning." },
    { id="enh_sundering", spec=263, spell="Sundering", moment="Cast", name="Sundering", event="SUCCEEDED", spellIDs={197214}, cue="earth", preset="subtle", cooldown=2, defaultOn=true, defaultSounds={1377102,4553587}, defaultDelays={0,100}, description="An earthen split for Sundering." },
    { id="enh_feral_spirit_doom_winds", spec=263, spell="Feral Spirit / Doom Winds", moment="Cast", name="Feral Spirit / Doom Winds", event="SUCCEEDED", spellIDs={51533,384352}, cue="major", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={569157,4556842}, defaultDelays={0,100}, description="Major Enhancement burst cooldown variants." },
    { id="enh_stormstrike_windstrike", spec=263, spell="Stormstrike / Windstrike", moment="Cast", name="Stormstrike / Windstrike", event="SUCCEEDED", spellIDs={17364,115356}, cue="air", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={1369104,1715016}, defaultDelays={0,80}, description="A sharp storm punctuation for the main spender variants." },
    { id="enh_lava_lash", spec=263, spell="Lava Lash", moment="Cast", name="Lava Lash", event="SUCCEEDED", spellIDs={60103}, cue="deepfire", preset="medium", cooldown=0.8, defaultOn=false, defaultSounds={1100351}, defaultDelays={0}, description="Optional fire spender punctuation." },
    { id="enh_fire_nova", spec=263, spell="Fire Nova", moment="Cast", name="Fire Nova", event="SUCCEEDED", spellIDs={333974}, cue="deepfire", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={1100351,1100352}, defaultDelays={0,90}, description="A fiery burst when talented." },
    { id="enh_primordial_storm", spec=263, spell="Primordial Storm / Surging Totem", moment="Cast", name="Primordial Storm / Surging Totem", event="SUCCEEDED", spellIDs={1218047,444995}, cue="major", preset="subtle", cooldown=3, defaultOn=true, defaultSounds={1369107,1715016}, defaultDelays={0,120}, description="Current burst and Totemic hero action variants." },
    { id="enh_ascendance", spec=263, spell="Ascendance", moment="Cast", name="Ascendance", event="SUCCEEDED", spellIDs={114051,467263}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={1369107,5259954}, defaultDelays={0,120}, description="Current Enhancement Ascendance variants." },

    { id="resto_shaman_chain_heal", spec=264, spell="Chain Heal", moment="Cast", name="Chain Heal", event="SUCCEEDED", spellIDs={1064}, cue="water", preset="medium", cooldown=1, defaultOn=true, defaultSounds={1965221,1965224}, defaultDelays={0,100}, description="A flowing cast accent for Chain Heal." },
    { id="resto_spirit_link_healing_tide", spec=264, spell="Spirit Link / Healing Tide", moment="Cast", name="Spirit Link / Healing Tide", event="SUCCEEDED", spellIDs={98008,108280}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={568624,1965231}, defaultDelays={0,120}, description="Major emergency totem variants." },
    { id="resto_riptide_rain", spec=264, spell="Riptide / Healing Rain", moment="Cast", name="Riptide / Healing Rain", event="SUCCEEDED", spellIDs={61295,73920}, cue="water", preset="medium", cooldown=1, defaultOn=true, defaultSounds={1937566,1965221}, defaultDelays={0,90}, description="Core wave and ground-heal accents." },
    { id="resto_healing_wave_unleash", spec=264, spell="Healing Wave / Unleash Life", moment="Cast", name="Healing Wave / Unleash Life", event="SUCCEEDED", spellIDs={77472,73685}, cue="water", preset="subtle", cooldown=1, defaultOn=false, defaultSounds={1965224,1937566}, defaultDelays={0,90}, description="Optional single-target cast and setup wave." },
    { id="resto_ascendance", spec=264, spell="Ascendance", moment="Cast", name="Ascendance", event="SUCCEEDED", spellIDs={114052}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={1965231,5259954}, defaultDelays={0,120}, description="A major restoration surge." },
    { id="resto_stormstream", spec=264, spell="Stormstream Totem", moment="Cast", name="Stormstream Totem", event="SUCCEEDED", spellIDs={1267016}, cue="major", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={1965231,569183}, defaultDelays={0,120}, description="The current Apex replacement for Healing Stream Totem." },
    { id="resto_call_ancestors", spec=264, spell="Call of the Ancestors", moment="Cast", name="Call of the Ancestors", event="SUCCEEDED", spellIDs={467646}, cue="major", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={1965231,5259954}, defaultDelays={0,100}, description="Farseer-only ancestor summon." },

    -- Monk
    { id="brew_breath_of_fire", spec=268, spell="Breath of Fire", moment="Cast", name="Breath of Fire", event="SUCCEEDED", spellIDs={115181}, cue="deepfire", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={613882}, defaultDelays={0}, description="A compact breath accent for Breath of Fire." },
    { id="brew_celestial_brew", spec=268, spell="Celestial Brew", moment="Cast", name="Celestial Brew", event="SUCCEEDED", spellIDs={322507}, cue="nature", preset="medium", cooldown=2, defaultOn=true, defaultSounds={606881,613937}, defaultDelays={0,100}, description="A jade shield shimmer for Celestial Brew." },
    { id="brew_invoke_niuzao", spec=268, spell="Invoke Niuzao", moment="Cast", name="Invoke Niuzao", event="SUCCEEDED", spellIDs={132578}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={1369101,4577695}, defaultDelays={0,120}, description="A grounded celestial call for Niuzao." },
    { id="brew_exploding_keg", spec=268, spell="Exploding Keg", moment="Cast", name="Exploding Keg", event="SUCCEEDED", spellIDs={325153}, cue="earth", preset="medium", cooldown=3, defaultOn=true, defaultSounds={4553587,568813}, defaultDelays={0,80}, description="A brief stone-and-dust burst for Exploding Keg." },
    { id="brew_keg_smash", spec=268, spell="Keg Smash", moment="Cast", name="Keg Smash", event="SUCCEEDED", spellIDs={121253}, cue="earth", preset="medium", cooldown=0.8, defaultOn=true, defaultSounds={4553587,568813}, defaultDelays={0,80}, description="A sturdy keg impact for the core builder." },
    { id="brew_blackout_tiger_palm", spec=268, spell="Blackout Kick / Tiger Palm", moment="Cast", name="Blackout Kick / Tiger Palm", event="SUCCEEDED", spellIDs={100784,100780}, cue="air", preset="expressive", cooldown=0.8, defaultOn=false, defaultSounds={1369372}, defaultDelays={0}, description="Optional martial spender and chi-builder punctuation." },
    { id="brew_purifying_brew", spec=268, spell="Purifying Brew", moment="Cast", name="Purifying Brew", event="SUCCEEDED", spellIDs={119582}, cue="nature", preset="medium", cooldown=1, defaultOn=true, defaultSounds={606881}, defaultDelays={0}, description="A clear mitigation release." },
    { id="brew_fortifying_brew", spec=268, spell="Fortifying Brew", moment="Cast", name="Fortifying Brew", event="SUCCEEDED", spellIDs={388917,322960}, cue="major", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={4577695,606881}, defaultDelays={0,120}, description="Current major defensive variants." },

    { id="ww_fists_of_fury", spec=269, spell="Fists of Fury", moment="Channeling", name="Fists of Fury", event="CHANNEL_START", spellIDs={113656}, cue="air", preset="medium", cooldown=2, defaultOn=true, defaultSounds={1369372,4556842}, defaultDelays={0,100}, description="One chi rush when Fists of Fury begins." },
    { id="ww_strike_of_windlord", spec=269, spell="Strike of the Windlord", moment="Cast", name="Strike of the Windlord", event="SUCCEEDED", spellIDs={392983}, cue="major", preset="subtle", cooldown=2, defaultOn=true, defaultSounds={1378203,1715016}, defaultDelays={0,90}, description="A storm surge for Strike of the Windlord." },
    { id="ww_rising_sun_kick", spec=269, spell="Rising Sun Kick", moment="Cast", name="Rising Sun Kick", event="SUCCEEDED", spellIDs={107428}, cue="nature", preset="medium", cooldown=0.9, defaultOn=true, defaultSounds={1369372}, defaultDelays={0}, description="A clear chi accent for the core kick." },
    { id="ww_whirling_dragon_punch", spec=269, spell="Whirling Dragon Punch", moment="Cast", name="Whirling Dragon Punch", event="SUCCEEDED", spellIDs={152175}, cue="air", preset="medium", cooldown=1.5, defaultOn=true, defaultSounds={1369372,4556842}, defaultDelays={0,90}, description="A spinning finisher when talented." },
    { id="ww_invoke_xuen", spec=269, spell="Invoke Xuen", moment="Cast", name="Invoke Xuen", event="SUCCEEDED", spellIDs={123904}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={606881,5259954}, defaultDelays={0,120}, description="A celestial tiger call for the major cooldown." },
    { id="ww_zenith", spec=269, spell="Zenith / Zenith Stomp", moment="Cast", name="Zenith / Zenith Stomp", event="SUCCEEDED", spellIDs={1249625,1272694}, cue="apex", preset="subtle", cooldown=3, defaultOn=true, defaultSounds={606881,5259954}, defaultDelays={0,100}, description="Current Apex active buttons." },
    { id="ww_touch_of_death", spec=269, spell="Touch of Death", moment="Cast", name="Touch of Death", event="SUCCEEDED", spellIDs={322109}, cue="major", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={1378203,1715016}, defaultDelays={0,90}, description="A decisive execution accent." },
    { id="ww_celestial_conduit", spec=269, spell="Celestial Conduit", moment="Channeling", name="Celestial Conduit", event="CHANNEL_START", spellIDs={443028}, capability="monk_conduit", cue="apex", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={606881,5259954}, defaultDelays={0,100}, description="A celestial channel opening when Conduit of the Celestials is selected." },

    { id="mw_enveloping_renewing_mist", spec=270, spell="Enveloping Mist / Renewing Mist", moment="Cast", name="Enveloping Mist / Renewing Mist", event="SUCCEEDED", spellIDs={124682,115151}, cue="nature", preset="medium", cooldown=1, defaultOn=true, defaultSounds={628392,606791}, defaultDelays={0,80}, description="Core jade HoT application accents." },
    { id="mw_revival_invoke_celestial", spec=270, spell="Revival / Invoke Celestial", moment="Cast", name="Revival / Invoke Celestial", event="SUCCEEDED", spellIDs={115310,322118,325197}, cue="major", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={613904,613937}, defaultDelays={0,100}, description="Major jade renewal and celestial variants." },
    { id="mw_celestial_conduit", spec=270, spell="Celestial Conduit", moment="Channeling", name="Celestial Conduit", event="CHANNEL_START", spellIDs={443028}, capability="monk_conduit", cue="apex", preset="subtle", cooldown=5, defaultOn=true, defaultSounds={606881,5259954}, defaultDelays={0,100}, description="A celestial channel opening when Conduit of the Celestials is selected." },
    { id="mw_soothing_mist", spec=270, spell="Soothing Mist", moment="Channeling", name="Soothing Mist", event="CHANNEL_START", spellIDs={115175}, cue="nature", preset="subtle", cooldown=1.5, defaultOn=false, defaultSounds={606881}, defaultDelays={0}, description="Optional one-time channel opening." },
    { id="mw_thunder_focus_tea", spec=270, spell="Thunder Focus Tea", moment="Cast", name="Thunder Focus Tea", event="SUCCEEDED", spellIDs={116680}, cue="nature", preset="medium", cooldown=2, defaultOn=true, defaultSounds={606881,613937}, defaultDelays={0,90}, description="A jade tea accent for the 30-second cooldown." },
    { id="mw_rising_sun_kick", spec=270, spell="Rising Sun Kick / Rushing Wind Kick", moment="Cast", name="Rising Sun Kick / Rushing Wind Kick", event="SUCCEEDED", spellIDs={107428,1250566,467307}, cue="nature", preset="medium", cooldown=0.9, defaultOn=true, defaultSounds={1369372,606881}, defaultDelays={0,90}, description="Current kick and talent replacement variants." },
    { id="mw_life_cocoon", spec=270, spell="Life Cocoon", moment="Cast", name="Life Cocoon", event="SUCCEEDED", spellIDs={116849}, cue="major", preset="subtle", cooldown=4, defaultOn=true, defaultSounds={606881,613937}, defaultDelays={0,100}, description="A major jade defensive." },
    { id="mw_vivify_sheiluns_gift", spec=270, spell="Vivify / Sheilun's Gift", moment="Cast", name="Vivify / Sheilun's Gift", event="SUCCEEDED", spellIDs={116670,399491}, cue="nature", preset="medium", cooldown=1.2, defaultOn=true, defaultSounds={628392}, defaultDelays={0}, description="Direct-heal and cloud-release accents; live metadata controls Casting exposure." },
}

for _, rule in ipairs(rules) do
    ns.AdditionalSpecRules[#ns.AdditionalSpecRules + 1] = rule
end
